### ISSUE TITLE
libc difference

### ISSUE THREAD

**Issue by lyssdod** [bebbo/libnix#10]
Hi, nice to see a project targeting AmigaOS today :)

As far as I can understand, that's kind of standard libc implementation for Amiga? If yes, can you please elaborate what's the difference from ulibc, for example? Thanks!

**Comment by tehKaiN** [comment]
Maybe this will help: https://github.com/bebbo/amiga-gcc/wiki/Libraries
Libnix and clib2 are historical relicts of Amiga development effort. AFAIK there's plan to merge them or leave only one some day.
