### ISSUE TITLE
__saveds does not work  when linking as .library

### ISSUE THREAD

**Issue by mheyer32** [bebbo/libnix#11]
Building a .library via 
-ramiga-lib -fbaserel

and using __saveds on a function will not link out of the box as the __restore_a4() symbol will be declared  missing during linking.

I found a workaround, by doing it manually:

```
static inline void RestoreA4(void)
{
    __asm volatile("\tlea ___a4_init, a4");
}
```

// This is a Task function for a Task spawned from the library. Usually I would have to use __saveds in front of it.
```
static void __stdargs MidiPlayerTask(void)
{
    RestoreA4();

    ....
}
```

**Comment by bebbo** [comment]
I recommend using members of your library struct instead of global/static variables.

- a6 wil always point to your struct - no need to init a register
- a4 is free for the compiler


```
struct MyLib {
  int bla;
};

int __regargs libfx1(int a, int b, char * c, struct MyLib * base asm("a6")) {
  base->bla += a;
  b += base->bla;
  *c = b;
  return base->bla;
}
```

yields something like:
```
_libfx1:
        add.l (a6),d0
        move.l d0,(a6)
        add.b d0,d1
        move.b d1,(a0)
        move.l (a6),d0
        rts
```

clean and easy

**Comment by bebbo** [comment]
=> a library should provide it's own  `__restore_a4()` method since the most (common) use for a4 in libraries is to provide an own data segment for each OpenLibrary.

**Comment by mheyer32** [comment]
Implementing my own __restore_a4() was what I initially did. But I believe, the libinit.c and libinitr.c (multi-base!) could probably provide it automatically. They both offer a
__GetDataSeg() function, which has access to __init_a4(). But it is inlined and not exposed outside the .o. 
It should be possible to implement __restore_a4() for both, regular and multi-base libs.

(From looking at libinitr.c it seems, they just make a full copy of the datasegment each time someone opens the lib, so each instance will have its own datasegment.)

**Comment by bebbo** [comment]
have a look: 2dadf5b4b9316b3a6b3bb44db4dca15ed2a49948

note that libinit.c can't be used with -fbaserel!

**Comment by mheyer32** [comment]
"note that libinit.c can't be used with -fbaserel! "

Please elaborate.

Does it  mean
"-fbaserel -ramiga-lib" 
Is a broken combination? If so, why?

What about 
"-fbaserel -ramigar-lib"  ?
