### ISSUE TITLE
Is there a  way to bootstrap stdio without the regular linker magic?

### ISSUE THREAD

**Issue by mheyer32** [bebbo/libnix#12]
DoomAttack loads plugins via LoadSeg. Thus, it requires the file to have a specific .o file first (it looks at the first few bytes for a magic word).

Despite -nostartfiles -nodefaultlib -nostdlib, the regular GCC linker will put _something_ in front of the .o file containing the magic cookie, thus DoomAttack will not register it as plugin.

I helped myself using  vlink to link the plugins from the produced .o files.

For many plugins, this is good enough - they don't use any stdlib stuff and are pretty barebones.
But some plugins want to do fancy things like printf.
It seems the plugins were written with MAXON-C and use a construct like below to get access to some standard libraries and the clib functionality:

```
		#ifdef __MAXON__
		InitModules();
		#endif
```
When the plugin gets shut down, the reverse will be done:
```
	#ifdef __MAXON__
	CleanupModules();
	#endif
```

Now the question is, does some mechanism like this exist for libnix (or GCC in general), too?

I.e. can some code be loaded into memory and made fully functional? This is a weird scenario as the process that loads the code already has a working runtime environment for stdio etc...

A similar scenario exists where if I spawn a new process  via CreateNewProcTags() also isn't properly setup to access stdlib functionality.

**Comment by mheyer32** [comment]
I think what I need to do is to emulate what ncrt0.s is doing; calling the ___INIT_LIST__ and ___EXIT_LIST__ entries manually, in the plugin's init function.

But I still need to be in control about the order of the linked objects in the resulting file. Is there a way? Maybe somehow with a special .spec file?

**Comment by bebbo** [comment]
> Despite -nostartfiles -nodefaultlib -nostdlib, the regular GCC linker will put something in front of the .o file containing the magic cookie, thus DoomAttack will not register it as plugin.

There is a `rts` in front of the header. Why should the linker omit code which is present in the assembler file or object file? /shrug

> But I still need to be in control about the order of the linked objects in the resulting file. Is there a way? 

The order *is* the given order of the parameters to ld.

> For many plugins, this is good enough - they don't use any stdlib stuff and are pretty barebones.
But some plugins want to do fancy things like printf.

You have to provide an API containing function pointers to all functions which are available to the plugins. A plugin must not call any other function or fully take care of itself.

**Comment by bebbo** [comment]
=> the answer is: no

**Comment by mheyer32** [comment]
> There is a rts in front of the header. Why should the linker omit code which is present in the assembler file or object file? /shrug

This is intentional, the cookie-check accounts for that.

To give an example, checkout
https://github.com/mheyer32/DoomAttack/tree/Plugins

type
`make c2p_Graffiti`

look at the resulting bin/DoomAttackSupport/c2p/Graffiti file.  The `C2P` marker is pretty much at the start of the file.

Now go into the Makefile and replace the line 

`$$(VLINK) $(PLIBS) -Bsymbolic -gc-all -x -S -s -sd -sc $$^ -o $$(${1}_TARGET)`

with the two below:

```
$$(STRIP)  $$(<D)/${1} -o $$(${1}_TARGET)
$$(CC) -nostartfiles $$^ -o $$(<D)/${1}
```
This basically replaces vlink with GCC's linker

Now the C2P marker moved further into the file; something got in front of it.

The create_objlist macro at the top of the Makefile moves the startup.asm file in front of the object files.

**Comment by bebbo** [comment]
You are using multiple code segments and the first segment is always the code segment name `.text`.
Thus the 2nd code segment named `CODE` is behind that.

And GetC2P accounts for that, since it searches all segments for the correct one.

I understand the different layouts, but I don't see the problem.

**Comment by mheyer32** [comment]
Oh, Ok, I had forgotten that GetC2P walks the segments. Unfortunately, it doesn't work - some more debugging to do. If I place the assembly files into .text everything works as expected.

> You have to provide an API containing function pointers to all functions which are available to the plugins. A plugin must not call any other function or fully take care of itself.

Yeah, thats what I'm afraid of.  I'll try bootstrapping libnix from within the plugin and see where this leads me. I won't file a bug if it doesn't work, promised :-)
 Are you aware of any showstoppers that'll make it futile right from the getgo?
I mean, plugin and main executable don't share their globals, so having a second "copy" of the runtime seems at least possible.
The only thing I could think of where initializing the plugin copy of libnix will break the main executable is if libnix is changing something in the current process itself; something that is unique to the process.

**Comment by mheyer32** [comment]
Update: I found the problem with walking the segment list:
`C2P = C2P->NextSeg;`  needs to be `  C2P = BADDR(C2P->NextSeg);`

**Comment by bebbo** [comment]
> Are you aware of any showstoppers that'll make it futile right from the getgo?

As long there aren't multiple processes, it should work either way. With API or with per plugin linked libs.

**Comment by mheyer32** [comment]
So, I managed to initialize stdio from within a plugin via walking the __INIT_LIST__ in  the startup of the plugin. (Took me quite some time until I figured out how its structured)

One thing that doesn't seem to work is to get __initlibraries() into the __INIT_LIST__, thus my first attempts failed, because __initstdio() relies on DOSBase being set up. I am doing that manually now, before walking __INIT_LIST__ and that works.

I'd like to understand, though, what is the canonical way to open dos.library? Is it via __initlibraries() or some other mechanism? If the former, how do I 'force' __initlibraries() into __INIT_LIST__?

I think the fact that it doesn't do it right now must be connected to -nostartfiles somehow... does -nostartfiles suppress library initialization?

**Comment by bebbo** [comment]
did you look at my nostartup example? 

http://eab.abime.net/showpost.php?p=1318994&postcount=13

**Comment by bebbo** [comment]
> I'd like to understand, though, what is the canonical way to open dos.library? Is it via __initlibraries() or some other mechanism? If the former, how do I 'force' __initlibraries() into INIT_LIST?

if a library is touched, __initlibrary is automatically added to the INIT_LIST.

Maybe you have an own DOSBase variable? Only use `extern ...DOSBase;`

**Comment by mheyer32** [comment]
> if a library is touched, __initlibrary is automatically added to the INIT_LIST.

That is what I expected, but it didn't happen. And yes, I refer to it through extern.
Your example is also calling __initlibraries() manually even though main() touches DOSBase?

**Comment by bebbo** [comment]
> 
> 
> > if a library is touched, __initlibrary is automatically added to the INIT_LIST.
> 
> That is what I expected, but it didn't happen. And yes, I refer to it through extern.
> Your example is also calling __initlibraries() manually even though main() touches DOSBase?

because my example does not hande the INIT_LIST.

**Comment by bebbo** [comment]
btw: this is the code from newlib crt0.c to handle the init list:
```
__entrypoint void callfuncs(int * q asm("a2"), unsigned short order asm("d2")) {
	for (;;) {
		int * p = q;
		unsigned short curprio = cleanupflag;
		unsigned short nextprio = -1;

		while (*p) {
			unsigned short prio = *((unsigned short *) p + 3) ^ order;

			// invoke
			if (prio == curprio)
				((void (*)(void)) *p)();

			// update next prio
			if (prio < nextprio && prio > curprio)
				nextprio = prio;

			p += 2;
		}
		if (nextprio == curprio)
			break;

		cleanupflag = nextprio;
	}
} 
```

**Comment by mheyer32** [comment]
Yep, that is pretty much the same (maybe a little more clever than mine :-) )as I do.
One thing that stumped me was that __INIT_LIST__ starts with the number of LONG entries in the very first LONG word in there.

> because my example does not hande the INIT_LIST.

Yep, so we're not really doing the same here. I'll try your example tonight and add the callfuncs example in there - lets see if __initlibraries() is going to show up :-)

**Comment by bebbo** [comment]
if it's in a repo, I may look as well... if I have time

**Comment by mheyer32** [comment]
https://github.com/mheyer32/DoomAttack/tree/Plugins

Has it.

make music_doomsound

should produce a plugin inside ./bin/plugin/DAMusic_DoomSndLibrary.plugin  with its intermediate files in build/plugins/Sound_and_Music/DoomSound_Library/

The plugin's entry point is in funcs.c / C_DAM_Init()
The startup code I whipped up is in ./plugin_runtime.c

Don't sweat it, its not super urgent :-)

**Comment by bebbo** [comment]
```
Disassembly of section .data:

 ___EXIT_LIST__:
        .long 0x00000004,___exitstdio,0x00000062,___exitmalloc,0x0000004e,0x00000000

 ___INIT_LIST__:
        .long 0x00000004,___initstdio,0x00000062,___initmalloc,0x0000004e,0x00000000
```

it's missing

**Comment by bebbo** [comment]
```
___EXIT_LIST__:
        .long 0x00000006,___exitstdio,0x00000062,___exitlibraries,0x00000044,___exitmalloc,0x0000004e,0x00000000

 ___INIT_LIST__:
        .long 0x00000006,___initstdio,0x00000062,___initlibraries,0x00000044,___initmalloc,0x0000004e,0x00000000
```

**Comment by mheyer32** [comment]
Another bug squashed :-D

**Comment by mheyer32** [comment]
Unfortunately, something is very broken now. 
Both, ADoom and DoomAttach crash immediately upon start

**Comment by bebbo** [comment]
rinse and repeat^^

**Comment by mheyer32** [comment]
I'm having trouble rebuilding my toolchain

Even after clean, clean-prefix I'm getting this:
[make libnix.log](https://github.com/bebbo/libnix/files/3140984/make.libnix.log)

Trying to rerun make all multiple times seems to always fail for a different file. It all looks like as if the
include path or mechanism is broken. Time to go to sleep :-)

**Comment by mheyer32** [comment]
Totally weird:
[make libnix.log](https://github.com/bebbo/libnix/files/3141025/make.libnix.log)


my environment:

```
matze@osboxes:~/amigatoolchain/amiga-gcc$ export
declare -x CLUTTER_IM_MODULE=""
declare -x DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-Umu8Zfra1g"
declare -x DEFAULTS_PATH="/usr/share/gconf/Lubuntu.default.path"
declare -x DESKTOP_SESSION="Lubuntu"
declare -x DISPLAY=":0.0"
declare -x GDMSESSION="Lubuntu"
declare -x GDM_LANG="en_US"
declare -x GNOME_KEYRING_CONTROL=""
declare -x GNOME_KEYRING_PID=""
declare -x GPG_AGENT_INFO="/home/matze/.gnupg/S.gpg-agent:0:1"
declare -x GTK2_MODULES="overlay-scrollbar"
declare -x GTK_IM_MODULE=""
declare -x GTK_MODULES="gail:atk-bridge"
declare -x HOME="/home/matze"
declare -x IM_CONFIG_PHASE="1"
declare -x INSTANCE=""
declare -x JOB="dbus"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US"
declare -x LD_LIBRARY_PATH="/usr/local/cuda-9.0/lib64:"
declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
declare -x LESSOPEN="| /usr/bin/lesspipe %s"
declare -x LOGNAME="matze"
declare -x LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
declare -x MANDATORY_PATH="/usr/share/gconf/Lubuntu.mandatory.path"
declare -x OLDPWD="/home/matze/amigatoolchain/amiga-gcc/projects"
declare -x PATH="/home/matze/amigatoolchain/amiga-gcc-out/bin/:/usr/local/cuda-9.0/bin:/home/matze/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
declare -x PWD="/home/matze/amigatoolchain/amiga-gcc"
declare -x QT4_IM_MODULE=""
declare -x QT_ACCESSIBILITY="1"
declare -x QT_IM_MODULE=""
declare -x QT_LINUX_ACCESSIBILITY_ALWAYS_ON="1"
declare -x QT_PLATFORM_PLUGIN="lxqt"
declare -x QT_QPA_PLATFORMTHEME="lxqt"
declare -x SAL_USE_VCLPLUGIN="gtk"
declare -x SESSION="Lubuntu"
declare -x SESSIONTYPE="lxsession"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_AUTH_SOCK="/run/user/1001/keyring/ssh"
declare -x TERM="xterm"
declare -x UPSTART_EVENTS="started xsession"
declare -x UPSTART_INSTANCE=""
declare -x UPSTART_JOB="lxsession"
declare -x UPSTART_SESSION="unix:abstract=/com/ubuntu/upstart-session/1001/2519"
declare -x USER="matze"
declare -x XAUTHORITY="/home/matze/.Xauthority"
declare -x XDG_CONFIG_DIRS="/etc/xdg/lubuntu:/etc/xdg/xdg-Lubuntu:/usr/share/upstart/xdg:/etc/xdg"
declare -x XDG_CONFIG_HOME="/home/matze/.config"
declare -x XDG_CURRENT_DESKTOP="LXDE"
declare -x XDG_DATA_DIRS="/etc/xdg/lubuntu:/usr/share/gdm:/var/lib/menu-xdg:/usr/share/Lubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop"
declare -x XDG_GREETER_DATA_DIR="/var/lib/lightdm-data/matze"
declare -x XDG_MENU_PREFIX="lxde-"
declare -x XDG_RUNTIME_DIR="/run/user/1001"
declare -x XDG_SEAT="seat0"
declare -x XDG_SEAT_PATH="/org/freedesktop/DisplayManager/Seat0"
declare -x XDG_SESSION_DESKTOP="Lubuntu"
declare -x XDG_SESSION_ID="c2"
declare -x XDG_SESSION_PATH="/org/freedesktop/DisplayManager/Session0"
declare -x XDG_SESSION_TYPE="x11"
declare -x XDG_VTNR="7"
declare -x XMODIFIERS=""
declare -x _LXSESSION_PID="2825"

matze@osboxes:~/amigatoolchain/amiga-gcc$ uname --all
Linux osboxes 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


```

**Comment by bebbo** [comment]
hm, my jenkins is building and travis too: https://travis-ci.org/bebbo/amiga-gcc

**Comment by bebbo** [comment]
if nothing helps:
```
git clone https://github.com/bebbo/amiga-gcc
cd amiga-gcc make all
```

and yes - make update is no longer mandatory^^

**Comment by mheyer32** [comment]
Yay! After re-cloning it compiles now. ADoom/DoomAttack do not crash anymore.
I still have an issue with DoomAttack (machine reboots upon second attempt to start it), but 
I think this is likely a problem on DoomAttack's side.

__initlibraries() is now contained in __INIT_LIST__

Thank you!

Closing.

**Comment by mheyer32** [comment]
I think you just fixed the restart issue.

**Comment by mheyer32** [comment]
There is still an issue.
How is __INIT_LIST__ supposed to behave when you don't use LibNix functions like printf(), yet use the LibNix DOSBase symbol?  I got trouble with the music_p61a plugin.... it will Use dos.library Open/Read etc, but not other libnix regular clib functions. In this case tyhe __initlibraries function doesn't even get emitted.

**Comment by mheyer32** [comment]
linking  against `-lstubs`  seems to do the trick. Is that to be expected?

**Comment by bebbo** [comment]
> 
> 
> linking against `-lstubs` seems to do the trick. Is that to be expected?

yes - -lstubs contains the mandatory object

**Comment by mheyer32** [comment]
Thumbs up!

Closing.
