### ISSUE TITLE
printf does not like time_t

### ISSUE THREAD

**Issue by githubaf** [bebbo/libnix#14]
When I try to print a time_t Variable with printf("%ld") it shows "0". Casted to long it works as expected.

[time_t_main.c.gz](https://github.com/bebbo/libnix/files/2613485/time_t_main.c.gz)

**Comment by bebbo** [comment]
try %lld since time_t is a 64 bit value

**Comment by githubaf** [comment]
You are right, %lld works.
Is that standard? On linux it works with %ld.
Also when I compile with -mcrt=clib2 it works with %ld.

**Comment by bebbo** [comment]
it depends how time_t is defined ^^

```
typedef /* unspecified */ time_t;
```

It's platform/compiler-specific. But you can cast it to a known type.

**Comment by githubaf** [comment]
OK, I see. 
Thanks for explanation.
