### ISSUE TITLE
'struct dirent' has no member named 'd_type'

### ISSUE THREAD

**Issue by arczi84** [bebbo/libnix#14]
Possible to get full dirent support ?

**Comment by bebbo** [comment]
>Possible to get full dirent support ?

What do you mean by "full dirent support"? Posix does not define `d_type`.

**Comment by arczi84** [comment]
This one does http://aminet.net/package/dev/c/vbcc_PosixLib .

**Comment by arczi84** [comment]
Looks like BSzill already added it:
https://github.com/bebbo/libnix/pull/3/commits/7951da30a49a905fd854e5d4084f2d8f4c5b3cc3

Can it be added to master?

**Comment by bebbo** [comment]
merged: f30eac4

**Comment by arczi84** [comment]
Cool, I look forward for prebuild toolchain.
