### ISSUE TITLE
-m68020:  vamos ----- ERROR in CPU Run #1 -----

### ISSUE THREAD

**Issue by githubaf** [bebbo/libnix#15]
After a while I compiled espak again. It starts with a simple test for CPU-Versions. The test fails now for 68020 CPU. 
The last working gcc toochain is from April, 2nd 2019

To reproduce just call 
make -f Makefile.amiga
in espeak workspace.

68000 works:

```
/home/developer/opt/m68k-amigaos_03Jun19/bin/m68k-amigaos-gcc  -noixemul -o cpu_requirements_test hello_world.c -lgcov -lm  -ldebug 
developer@cn-vm-afritsch:~/espeak_src/espeak-source/src$ vamos cpu_requirements_test
Hello world, Pi=3.141593

```

68020 fails:
```
developer@cn-vm-afritsch:~/espeak_src/espeak-source/src$ /home/developer/opt/m68k-amigaos_03Jun19/bin/m68k-amigaos-gcc  -m68020 -o cpu_requirements_test -noixemul -Wall -pedantic -I. hello_world.c
developer@cn-vm-afritsch:~/espeak_src/espeak-source/src$ vamos cpu_requirements_test
16:03:02.280    machine:  ERROR:  ----- ERROR in CPU Run #1 -----
16:03:02.281    machine:  ERROR:  Run: 'cpu_requirements_test': Initial PC=002094, SP=005de0
16:03:02.281    machine:  ERROR:  PC=000004fe  SR=--Z--
16:03:02.281    machine:  ERROR:  D0=00000000  D1=00000000  D2=ffffffff  D3=00000000  D4=00000062  D5=00000062  D6=00000000  D7=00000000
16:03:02.281    machine:  ERROR:  A0=00006044  A1=00006180  A2=0000a14c  A3=00003c28  A4=00000000  A5=00003d5c  A6=00001ae8  A7=00005dae
16:03:02.281    machine:  ERROR:  SP-32=3c180000 SP-28=3c380000 SP-24=000000 SP-20=133c0000 SP-16=3a4affff SP-12=ffff0000 SP-08=000000 SP-04=387c0000
16:03:02.281    machine:  ERROR:  SP+00=050000 SP+04=5ff9218a SP+08=27040000 SP+12=38a00000 SP+16=387c0000 SP+20=1ae80000 SP+24=362affff SP+28=ffff0000
16:03:02.282    machine:  ERROR:  InvalidCPUStateError: Invalid CPU State: pc=005ff9: m68k Exception: sr=0005
16:03:02.282       main:  ERROR:  vamos failed!
16:03:02.283     libmgr:WARNING:  shutdown: can't expunge 1 vamos libs/devs!

```

**Comment by bebbo** [comment]
hahaha - that's not that easy, since the code to display the message is using 68020+ instuctions. ROFL

**Comment by bebbo** [comment]
It was sheer luck that the code path did not use any 68020+ instructions.
And it's a futile attempt to use 68020 code to check for 68020 presence.

It's possible to support that again, but too much effort for nothing.

**Comment by mheyer32** [comment]
Maybe you could override the recipe for the startup files only to use -m68000?

**Comment by bebbo** [comment]
the startup files are pure asm and not the problem.
It's possible but not worth the effort.

**Comment by bebbo** [comment]
and the real problem starts if you consider `-fbaserel32` - do you want non baserel code in your lib?

**Comment by githubaf** [comment]
We cannot require anything, your work is very much appreciated. So don't get me wrong.

But,...
the information "Need a 68020 or higher CPU" instead if crashing sounds very reasonable to me. So sounds the information "Need some FPU to run". 

Could you explain why it doesn't work any longer now and where the real problem is?
Before calling main() the AttnFlags are checked, a message is displayed and the progam is left. I looked into the executables from 2.April and from 10. June. In the working 2.April executable there is an ___Init_List___ containing nocommandline, cpucheck, initcpp, initlibraries, initstdio and initmalloc. In the executable from 10.June this list seems to be much smaller, only nocommandline, inistdio initmalloc and initlibraries are in that list. So I guess there is no call to cpucheck() at all and the program crashes therefore?

You said there would be an even bigger problem with -fbaserel32? Could you explain?

**Comment by bebbo** [comment]
>Could you explain why it doesn't work any longer now and where the real problem is?

gcc now creates better(?)/differentcode that really uses the 68020+ features, such as indirect addressing.
And to display an error message, it's some libs, checks and some code is used, which now contains such instructions a 68000 does not understand.

> You said there would be an even bigger problem with -fbaserel32? Could you explain?

It never worked with -fbaserel32, since the startup code stores stuff a4 based with 32 bit offsets. These fail on 68000.

The best approach seems to be using a recoverable exec alert and display some reasonable value (e.g. 68020).

I don't say, it can't be done, but it's work for ... almost nothing

**Comment by bebbo** [comment]
done enough - eat or die ^^

**Comment by githubaf** [comment]
I had some build issues during the weekend, but now I was able to test wit your commits from yesterday, June 16th.

I knew you could do that!
:-)

But...
Personally I liked the Request() call much more than the Alert(). I did not fully understand the probem with Request().

More important:
The check for the FPU is missing if started from CLI.
In 

sources/startup/nlbcrt0.S
and 
 sources/startup/nlrcrt0.S

you seem to test for 68020 only:

```
| check cpu
		btst.b  #1,1+Attn(a6)
		jne cpuok

| alert
		move.l  #0x68020,d7
		jsr -0x6c(a6)

		moveq.l	#20,d7
		bra		cleanup

cpuok:

```

**Comment by bebbo** [comment]
some info:
- a4 based access e.g. to SysBase, IntuitionBase, .. whatever with 32bit offset yield invalid code for 68000
- the full code path has to be considered to be 68000 friendly -> keep it as simple as possible
 - right now there is also no library which checks for FPU since this would require a lib built with -mhard-float. There is no pre-build lib which checks for FPU.
 - the bits are additiv, all CPUs > 68020 will also set the 68020 bit.

feel free to provide pull requests.

**Comment by githubaf** [comment]
I am still experimenting.

In the code there is
#ifdef __HAVE_68881__

What compiler/linker options do I need for compiling my testprogram to have this #ifdef active? When I just add -m68020 -m68881 and than disassemble with objdump the code inside #ifdef __HAVE_68881__ seems not to be present.

`m68k-amigaos-gcc  -noixemul -o cpu_requirements_test hello_world.c -lgcov -l68881  -ldebug -Wl,-Map=speak.map,--trace`

**Comment by githubaf** [comment]
OK. Then the actual issue can be considered solved. Thank you.
I continue experimenting,
