### ISSUE TITLE
SDL "Fire-0.3" demo 

### ISSUE THREAD

**Issue by arczi84** [bebbo/libnix#16]
"Fire-0.3" demo from https://su2.info/demos/
displays only half of particles on the screen.
Tried various -O flags with same result.
Works on older gcc's.

_Originally posted by @arczi84 in https://github.com/bebbo/amiga-gcc/issues/5#issuecomment-457964025_

**Comment by bebbo** [comment]
the double/float<->unsigned/long conversion functions using mathieee*.library do not work as expected.

**Comment by bebbo** [comment]
the affected functions are now taken from libgcc which are correct.

please test

**Comment by arczi84** [comment]
Yes, it works now.
