### ISSUE TITLE
nix13 on a500

### ISSUE THREAD

**Issue by alexalkis** [bebbo/libnix#17]
git clone https://github.com/alexalkis/a68k
make

the executable gurus 8000 0003 on a500.  The same executable runs on A1200.

**Comment by bebbo** [comment]
> Also, if I may suggest....you could go for cli_StandardOutput instead of Output() for stderr.

what's the difference / benefit of using `cli_StandardOutput`?

**Comment by alexalkis** [comment]
well, for 1.3 it helps if you redirect a cli command (say 'list' or something to that effect) to a file (list >foo.txt) and you can have fprintfs go to the cli window (instead of going to the redirected file)

**Comment by bebbo** [comment]
please test

**Comment by alexalkis** [comment]
ok, printing usage uses stderr.  So stderr gives no output.
Can't figure out the hard-disk/floppy behavior.

**Comment by alexalkis** [comment]
ok, works from hard disk as well. (it just didn't gave me the error messages I was expecting, due to stderr not printing anything).

To sum up. All works, except stderr.

**Comment by alexalkis** [comment]
I think you have one BADDR too many 
I think this
fp->lx_fh = (BPTR)BADDR(cli->cli_StandardOutput);
should be
fp->lx_fh = cli->cli_StandardOutput;

**Comment by bebbo** [comment]
> I think you have one BADDR too many

uhm - yes

changed this

**Comment by alexalkis** [comment]
works perfectly! Thanks!

**Comment by alexalkis** [comment]
If you add '-DUSEAMIGAOS' in the Makefile's CFLAGS it replaces c lib file operations with DOS library (library function calls).  It crashes on 1.3 while the same exe runs in >=2.0

(I've added two samples in the git in 'samples/' folder.  run a68k gal.asm to see the crash on 1.3)

**Comment by bebbo** [comment]
please test

**Comment by alexalkis** [comment]
doesn't link
/opt/amiga/gcc6/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /opt/amiga/gcc6/m68k-amigaos/libnix/lib/libb/libnix.a(__stdio.o):__stdio.o:(.data+0x0): multiple definition of `__sF'; /opt/amiga/gcc6/m68k-amigaos/libnix/lib/libb/libnix13.a(__sf.o):(.data+0x0): first defined here

(I haven't cleaned, just git pull, make update, make all)

**Comment by bebbo** [comment]
you need a
```
make clean-libnix
```
before make all

**Comment by alexalkis** [comment]
Yeap, works with -DUSEAMIGAOS (and without) :) 
Thanks!

**Comment by alexalkis** [comment]
hmmm, today's update makes it a little faster and a little bigger.
baseline was 131 lines per sec (emulated a500) on gal.asm with 49616 bytes of executable.
Now it's 135 lines per sec, size 51680 bytes
(sas is at 142 lines per sec, size 52552 bytes)

**Comment by bebbo** [comment]
I get different values:

running a68k -q gal.asm yields:

sc: 154 to 155 lines/s - with optimizersize or optimizertime
gcc: 149 l/s with -Os and 159 l/s with -O3

**Comment by alexalkis** [comment]
with -q I get
baseline: 143lps
today's build: 148lps
sas c: 154lps

(all optimize for size)

**Comment by bebbo** [comment]
so you are only testing -Os
