### ISSUE TITLE
"console.device failed to load" when autoloaded

### ISSUE THREAD

**Issue by dwhinham** [bebbo/libnix#17]
The following code triggers auto library loading of the `console.device`, as `RawKeyConvert()` is a function inside the device:

```
#include <devices/inputevent.h>
#include <proto/console.h>
#include <stdint.h>

int main()
{
	struct InputEvent ie = { 0 };
	char buffer;
	int32_t res = RawKeyConvert(&ie, &buffer, sizeof(buffer), NULL);
}
```

Compiled with `m68k-amigaos-gcc -mcrt=nix13 test.c -o test` and running it, `console.device failed to load` is printed to the shell and the program exits (at least on Kickstart 3.1). This has been occurring since the recent changes that always enable library loading.

I saw that the libnix code just callls `OpenLibrary()` on the `console.device` - is this legal?

In my own code, to get access to this function, I use `OpenDevice()` to open the `console.device` and then assign `io_Device` to base address variable `ConsoleDevice` before I can use RawKeyConvert (see [autodocs](http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_3._guide/node0104.html)).

I have tried to work around this by setting `__initlibraries` to an empty function (disable auto loading), but then even an empty `int main() { return 0; }` will crash, so I'm not sure what else I need to implement so I can do my own library initialisation.

Any help appreciated! :)

**Comment by bebbo** [comment]
ups :-) I simply generated the stabs for all fd files - and forgot to drop the devices.

**Comment by bebbo** [comment]
the console.device is no longer treated like a library and you can/must open/close it on your own.

**Comment by dwhinham** [comment]
Great, thankyou - it already pulled and tested, and it works :) I can just continue to use my existing code that deals with the console.device.

Out of interest, do you have a minimal example for using manual library loading for other libraries? As mentioned above I've tried an empty `__initlibraries` but even an empty main crashes - any ideas?

Thanks again!

**Comment by bebbo** [comment]
you also have to disable command line parsing, which uses dos.library
```
short __nocommandline = 0;
```

**Comment by bebbo** [comment]
(but why would you invent your own library loading /shrug :-) )

**Comment by dwhinham** [comment]
Perfect, thankyou for the super quick replies - it works! :)

It's a good question - I wrote some code previously for VBCC that manually opens all the libraries, and I didn't actually know that libnix can automatically handle everything, which is nice. I will probably adapt the code to just use the automatic method, but I just wanted to understand how it works and how to control it before I decide to remove all my manual library loading.

Thanks again! :smiley:
