### ISSUE TITLE
FPU check missing in projects/libnix/sources/nix/misc/__cpucheck.c

### ISSUE THREAD

**Issue by githubaf** [bebbo/libnix#19]
Please see my comment to the merge 4715c66a7c714e1e824baabc0caa2f6c1149387a

**Comment by bebbo** [comment]
no pushing please

**Comment by githubaf** [comment]
Please see my two pull requests from today,

**Comment by bebbo** [comment]
now there is finally a check for 68881 too - if a 68881 library variant is linked.
