### ISSUE TITLE
strtol and strtoul is broken

### ISSUE THREAD

**Issue by BSzili** [bebbo/libnix#2]
All of the tests from libiberty's testsuite fail:
https://github.com/gcc-mirror/gcc/blob/master/libiberty/testsuite/test-strtol.c
I compiled it like this:
> m68k-amigaos-gcc -noixemul -m68020 -o test-strtol test-strtol.c

For standalone compilation, I made a dummy libiberty.h with this content

>#define SIZEOF_LONG 4
#define HAVE_STDLIB_H
#define HAVE_STRING_H
#define HAVE_UNISTD_H

**Comment by bebbo** [comment]
I killed cytpes.h...

**Comment by bebbo** [comment]
please test

**Comment by BSzili** [comment]
Problem solved.
