### ISSUE TITLE
libbases/timer.c tries to OpenLibrary timer.device

### ISSUE THREAD

**Issue by Midar** [bebbo/libnix#20]
The following triggers an attempt to OpenLibrary() timer.device:

https://github.com/bebbo/libnix/blob/master/sources/stubs/libbases/timer.c#L10

This of course fails, rendering any program that links that stub (e.g. by using GetSysTime) to fail to start at all.

**Comment by mheyer32** [comment]
Midar, did you notice this above the code in question?

`#if 0 && defined (__libnix__)`

**Comment by Midar** [comment]
Oh, turns out I still had an old version and it's already fixed :).
