### ISSUE TITLE
freopen defined twice

### ISSUE THREAD

**Issue by mheyer32** [bebbo/libnix#20]
https://github.com/bebbo/libnix/commit/ce1ba64e130c3dfafdc60639e5d74636504a99d1

introduced a new freopen implementation. I guess, it either needs to be moved into freopen.c or freopen.c needs to go. Otherwise I'm getting:

/home/matze/amigatoolchain/amiga-gcc-out/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /home/matze/amigatoolchain/amiga-gcc-out/m68k-amigaos/libnix/lib/libm020/libb/libnix.a(open.o):open.o:(.text+0x2b0): multiple definition of `freopen'; /home/matze/amigatoolchain/amiga-gcc-out/m68k-amigaos/libnix/lib/libm020/libb/libnix.a(freopen.o):(.text+0x0): first defined here

**Comment by bebbo** [comment]
forgot to commit this - thanks.
