### ISSUE TITLE
undefined reference to __truncf

### ISSUE THREAD

**Issue by th-otto** [bebbo/libnix#22]
Calling truncf() from either C- or C++-Code does not give a warning or error, but fails when linking with -mcrt=nix20:

```
$ cat foo.c
#include <math.h>

float x, y;

int main(void)
{
        x = truncf(y);
        return 0;
}
$ m68k-amigaos-gcc -Wall -O2 -mcrt=nix20 foo.c
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /tmp/cciKnODr.o:(.text+0x8): undefined reference to `truncf'
collect2: error: ld returned 1 exit status

$cat foo.cc
#include <cmath>

float x, y;

int main(void)
{
        x = truncf(y);
        return 0;
}
$ m68k-amigaos-g++ -Wall -O2 -mcrt=nix20 foo.cc
/opt/amiga/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /tmp/cctyN072.o:/tmp/cctyN072.o:(.text+0x8): undefined reference to `truncf'
collect2: error: ld returned 1 exit status
```

truncf() is only present in newlibs libm.a, but not in libnix.

Of course you could prevent the scenarioa above by using trunc(), but the following C++ code will also generate references to truncf:

```
$cat test.cc
#include <math.h>

extern "C" {
unsigned int GetTimeElapsed(void);
}
extern unsigned int mulSampleSize;
extern unsigned int mdwLength;

class RHSound
{
private:
	int								PlaySound	( unsigned int uiSamplePosition = 0 );
public:
	RHSound	();
	~RHSound( void );

	void							Hourglass( void );
								
};

void RHSound::Hourglass( void )
{
	// Get elapsed time since sample start
	unsigned int	dwTimeElapsed;
	float	fPosition;

	dwTimeElapsed = GetTimeElapsed( );

	// Compute sample position
	fPosition = static_cast< float >( dwTimeElapsed ) / static_cast< float >( mdwLength );

	fPosition = fPosition - floor( fPosition );

	// Convert to sample position
	unsigned int	uiSampleLength;
	unsigned int	uiSamplePosition;

	uiSampleLength	=  mulSampleSize;
	uiSamplePosition= (unsigned int)(static_cast< float >( uiSampleLength ) * fPosition);

	PlaySound( uiSamplePosition );
}

$ m68k-amigaos-g++ -s -O2 -m68020 -mcrt=nix20 -msoft-float -S RHsound.cpp -o - | grep trunc
        jsr _truncf

```

I also wonder: is the math library in the libnix directory needed at all?

**Comment by bebbo** [comment]
> I also wonder: is the math library in the libnix directory needed at all?

 - the libnmix math functions are using math*.library.
 - the libgcc math functions aren't using the math coprocessor

**Comment by bebbo** [comment]
please test

**Comment by th-otto** [comment]
Yes, that worked, thx for the quick solution. Had to do a "make clean" first, without it the new sources were not compiled.

Any idea why the compiler generates a call to truncf in the 2nd example?

**Comment by bebbo** [comment]
> 
> 
> Yes, that worked, thx for the quick solution. Had to do a "make clean" first, without it the new sources were not compiled.

the current Makefiles  are not that smart...

> Any idea why the compiler generates a call to truncf in the 2nd example?

how would you convert a float into an int?

 What about

```
uiSamplePosition = uisampleLength * (dwTimeElapsed % mdwLength) / mdwLength;
```

**Comment by th-otto** [comment]
> how would you convert a float into an int?

by a cast to an int, which results in a call to __fixsfsi, but not to truncf

Also it seems to caused by that 
```
fPosition = fPosition - floor( fPosition );
```
when i comment that out, the reference disappears.

**Comment by bebbo** [comment]
and it should be `floorf`

so `truncf` might be the result by some optimization of `<floatvar> = floor( <float with positive value>)` -> `truncf`

**Comment by th-otto** [comment]
Most likely, yes. But then it looks like a configuration problem, the compiler should not generate calls to functions that are not there. BTW the atari cross-compiler does not do that (the math-library in use there also lacks all the *f variants of math functions).

**Comment by bebbo** [comment]
The compiler knows nothing about the libraries.

Feel free to configure a fork the way you like it. I prefer using 'float' functions for float objects.

**Comment by th-otto** [comment]
> The compiler knows nothing about the libraries.

Unfortunately, that is not entirely true: [https://github.com/bebbo/gcc/blob/46a3cdd20ad090e6e126c8d214894ac0cebcd3b5/gcc/doc/tm.texi#L5310](url)

This macro essentially tells the compiler whether the target library has c99 functions or not. You can also grep for it in the sources, it is overridden by a lot of targets.

**Comment by bebbo** [comment]
> 
> 
> > The compiler knows nothing about the libraries.
> 
> Unfortunately, that is not entirely true: https://github.com/bebbo/gcc/blob/46a3cdd20ad090e6e126c8d214894ac0cebcd3b5/gcc/doc/tm.texi#L5310
> 
> This macro essentially tells the compiler whether the target library has c99 functions or not. You can also grep for it in the sources, it is overridden by a lot of targets.

There isn't "the target library". The Amiga gcc version supports mutiple libraries. Newlib provides all math functions, libnix not yet, and there is also clib2.

With that setting you may define what the compiler should expect - but it still does not know what the linker will use.

**Comment by th-otto** [comment]
> There isn't "the target library"

Yes, i realized that by now ;)

If you look at other targets, you will notice that this macro is hooked to a function (no_c99_libc_has_function in most cases, there are some commonly used functions for this purpose defined in gcc/targhook.c). Theoretically, you can hook it to your own function, and return different values depending on which library is in use. IIRC there are also some other platforms with more than one library, but maybe their code is not part of the main repo.

For now, it should work. Thx again.

**Comment by bebbo** [comment]
Since you can't predict which options will be used when linking, a decision at compile time is useless.

Therefore the compiler is allowed to use all functions and there is a problem if an insufficient library is linked. Over time the libraries will be completed and everything is fine.
