### ISSUE TITLE
1.3 uninitialized something? 

### ISSUE THREAD

**Issue by alexalkis** [bebbo/libnix#23]
In the archive there is hcc.adf
From shell just run hcc, no arguments. Should display usage and exit.

This runs on a500+ but crashes on a500 (8000 0003).  Something is not initialized correctly for 1.3?

From top directory you can try (if you have fs-uae on linux at least :)
make run 
and
make run model=a500+

[source.zip](https://github.com/bebbo/amiga-gcc/files/3671902/source.zip)

**Comment by bebbo** [comment]
`Address error at __fillenviron+98`

**Comment by bebbo** [comment]
please test

a clean-libnix is required

**Comment by alexalkis** [comment]
Yeap, fixed.

Thanks!
