### ISSUE TITLE
error: '_mbstate_t' has not been declared

### ISSUE THREAD

**Issue by arczi84** [bebbo/libnix#25]
What do I need to define to make _mbstate_t work ?

> [ 97%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/DiabloUI/text_draw.cpp.obj
> In file included from D:/amiga-gcc2/lib/gcc/m68k-amigaos/6.5.0b/include/c++/cstdlib:75:0,
>                  from D:/amiga-gcc2/lib/gcc/m68k-amigaos/6.5.0b/include/c++/bits/stl_algo.h:59,
>                  from D:/amiga-gcc2/lib/gcc/m68k-amigaos/6.5.0b/include/c++/algorithm:62,
>                  from /D/dev/dev-master/devilutionX-master/SourceX/DiabloUI/selhero.cpp:3:
> D:/amiga-gcc2/m68k-amigaos/sys-include/stdlib.h:108:64: error: '_mbstate_t' has not been declared

**Comment by bebbo** [comment]
`#include <string>`

**Comment by arczi84** [comment]
Sorry, didn't help.

**Comment by bebbo** [comment]
do you include something else before?

**Comment by arczi84** [comment]
Only project headers

https://github.com/diasurgical/devilutionX/blob/master/SourceX/DiabloUI/text_draw.cpp

śr., 9 paź 2019, 13:17 użytkownik bebbo <notifications@github.com> napisał:

**Comment by arczi84** [comment]
Don't know what changed but newest sources fixed the problem.

śr., 9 paź 2019 o 14:34 Arti <arturjarosik@gmail.com> napisał(a):

**Comment by bebbo** [comment]
dobrze

**Comment by arczi84** [comment]
:)

**Comment by MBeijer** [comment]
https://github.com/bebbo/amiga-gcc/issues/132

**Comment by arczi84** [comment]
Worked for me after toolchain update, hmm.
