### ISSUE TITLE
Link libs bug

### ISSUE THREAD

**Issue by arczi84** [bebbo/libnix#27]
Created link libs have undefined references.
They can only be linked with
` -Wl,--whole-archive -lpng16  -Wl,--no-whole-archive `

**Comment by bebbo** [comment]
Could you be more verbose, please?

**Comment by arczi84** [comment]
Compiled with gcc version 6.5.0b 191023121710.

I have compiled libs with this script :https://github.com/AmigaPorts/devilutionX/tree/master/Packaging/amiga

**Comment by arczi84** [comment]
Another bug in compiled libSDL (scroll to the bottom)
https://circleci.com/gh/diasurgical/devilutionX/5346?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by bebbo** [comment]
> 
> 
> Compiled with gcc version 6.5.0b 191023121710.
> 
> I have compiled libs with this script :https://github.com/AmigaPorts/devilutionX/tree/master/Packaging/amiga

If I run that script it uses normal gcc:

```
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
```

**Comment by arczi84** [comment]
Use this 
`cmake  -G"MSYS Makefiles" -DCMAKE_TOOLCHAIN_FILE=./m68k-amigaos.cmake -DM68K_TOOLCHAIN_PATH=/<your_path>/amiga-gcc2 -DM68K_CPU=68060 -DM68K_FPU=hard ..`

**Comment by arczi84** [comment]
I've found that in SDL makefile -noixemul is not used , hmm ...

**Comment by arczi84** [comment]
But both gives:
```
devilutionx: code reloc for _Apollo_EnableAMMX is out of range: 00000000
devilutionx: code reloc for _Apollo_EnableAMMX is out of range: 00000000
devilutionx: code reloc for _ApolloCopyRect is out of range: 00000000
devilutionx: code reloc for _ApolloKeyRGB565toRGB565 is out of range: 00000000
devilutionx: code reloc for _ApolloBGRAtoRGB565 is out of range: 00000000
devilutionx: code reloc for _ApolloARGBtoRGB565 is out of range: 00000000
devilutionx: code reloc for _ApolloRGBtoRGB565 is out of range: 00000000
devilutionx: code reloc for _ApolloBGRtoRGB565 is out of range: 00000000
devilutionx: code reloc for _ApolloARGBtoRGB24 is out of range: 00000000
devilutionx: code reloc for _ApolloBGRAtoRGB24 is out of range: 00000000
devilutionx: code reloc for _ApolloBGRtoRGB24 is out of range: 00000000
devilutionx: code reloc for _ApolloARGBtoBGRA is out of range: 00000000
```

Doesn't happen with 

`gcc version 6.5.0b 190922223344 (GCC)`

**Comment by bebbo** [comment]
```
> m68k-amigaos-objdump -m68040 -d video/apollo/blitapollo.ao 

video/apollo/blitapollo.ao:     file format amiga


Disassembly of section code:
...
```
that section must(?)/should be named .text

**Comment by arczi84** [comment]
Ok, fixed :)
