### ISSUE TITLE
printf of a float with -noixemul doesn't work

### ISSUE THREAD

**Issue by ronybeck** [bebbo/libnix#28]
Am I missing something obvious?  When compiling with -noixemul, printf stops printing floats and doubles.  It prints simple "%f".

Example: compiling the following with m68k-amigaos-gcc -noixemul -m68080 -o test test.c

```
#include <stdio.h>

int main( int argc, char **argv)
{
	float test = 3.2f;
	printf( "Testing %f\n", test );
	return 0;
}
```
The output is "Testing %f".

Removing "-noixemul" from compilation parameters restores the corrected behavior.  Printing integers seems to work correctly.

**Comment by bebbo** [comment]
please add `-lm`

**Comment by ronybeck** [comment]
The result is the same.  Here is how I compiled just now:

m68k-amigaos-gcc -Wall -noixemul -m68080 -lm -o test test.c

**Comment by bebbo** [comment]
the order is also important, you want the math lib searched after your test.c file to pick the printf from the math lib:

`m68k-amigaos-gcc -Wall -noixemul -m68080 -o test test.c -lm`

**Comment by ronybeck** [comment]
That works!  It was my own stupidity after all.  Thank you very much!
