### ISSUE TITLE
string.h inconsistency

### ISSUE THREAD

**Issue by mheyer32** [bebbo/libnix#3]
When including string.h in -O0 mode, __NO_INLINE__ is set and a few functions will be forward-declared. In optimization mode, inlineing is enabled  __NO_INLINE__ is not defined and strsup.h gets included.

It happens to be that strsup.h declares/defines a few more functions than getting forward-declared in string.h when __NO_INLINE__ is set. This leads to, for instance, strupr() being available in optimized mode, but leading to compilation error in -O0 mode.

**Comment by bebbo** [comment]
please test

**Comment by mheyer32** [comment]
Fixed! Thanks!
