### ISSUE TITLE
Cannot `seekp` past EOF on R/W file

### ISSUE THREAD

**Issue by glebm** [bebbo/libnix#30]
Example:

```c+++
#include <iostream>
#include <fstream>

int main()
{
	std::fstream x("myfile.dat", std::ios::in | std::ios::out | std::ios::binary | std::ios::trunc);
	x.exceptions(std::fstream::failbit | std::fstream::badbit);
	x.seekp(65640, std::ios::beg);
	return 0;
}
```

Illegal seek
Same happens with an existing file without `std::ios::trunc` if the position is beyond EOF

**Comment by bebbo** [comment]
please test

**Comment by glebm** [comment]
If I then do a write after the seek, will it write at the correct position?

We use this for skipping the header section; at the end, once we know what to put there, we seekp back to the start of the file and write the header.

Can't easily test yet, need to figure out how to update the toolchain etc. /cc @MBeijer

**Comment by bebbo** [comment]
> 
> 
> If I then do a write after the seek, will it write at the correct position?

no - since the Amiga does not support sparse files...

> We use this for skipping the header section; at the end, once we know what to put there, we seekp back to the start of the file and write the header.

this means that a seek beyond the file end in write mode should extend the file - and fill it with garbage^^

> Can't easily test yet, need to figure out how to update the toolchain etc. /cc @MBeijer

go to the folder where the tool chain was built, then do a `make update && make libnix` to update.

**Comment by MBeijer** [comment]
@glebm If you want to use docker: https://github.com/AmigaPorts/m68k-amigaos-gcc

**Comment by glebm** [comment]
Well it sounds like it doesn't work yet, so I should wait before testing. Filling with garbage is the right thing to do; some systems guarantee zeros instead of garbage.

**Comment by bebbo** [comment]
soka - the file is now extended somehow (with garbage) and the position is set correctly
