### ISSUE TITLE
Compiling with FPU support, exe fails to run without mathieeedoubtrans.library

### ISSUE THREAD

**Issue by TCH68k** [bebbo/libnix#32]
I've compiled the program like this:
```
m68k-amigaos-gcc -mcrt=nix20 -mcpu=68030 -march=68030 -m68881 -lm main.c -o main
```
But the program fails to start; it says, it needs mathieeedoubtrans.library. Did i something wrong, or is this a bug?

The host system is Linux AMD64.

**Comment by bebbo** [comment]
see af4270f

**Comment by TCH68k** [comment]
I've rebuilt the entire SDK (it was long overdue anyway):
```
git clone https://github.com/bebbo/amiga-gcc
cd amiga-gcc
make update
make all -j7
```
And then i compiled:
```
m68k-amigaos-gcc -mcrt=nix20 -mcpu=68030 -march=68030 -m68881 -mhard-float -lm -lamiga main.c -o main
```
Nothing changed. Still requires mathieeedoubtrans.library. It does not change things if i omit the option `-lamiga` or `-m68881` or both.

**Comment by bebbo** [comment]
> Rebuild your libnix libs **once this is live** and try again with libnix.

you could modify Makefile.gcc6 manually and replace `-m68881` with `-m68881 -mhard-float` in projects/libnix. Note that this will break future `git pull`s ...

Then do `make clean-libnix` and `make libnix`

**Comment by TCH68k** [comment]
Sorry, i thought the commit you linked in meant that it is live. When will it be then?

I'd rather stick to the upstream version of everything, i do not want to break anything.

**Comment by bebbo** [comment]
it's live:
```
cat >nix32.c <<EOF
#include <stdio.h>
int main(int argc, char ** argv) {
        printf("%e\n", 3.14159d * (double)argc);
        return 0;
}
EOF
m68k-amigaos-gcc nix32.c -o nix32 -Os -noixemul -m68020 -m68881 -mhard-float -lm
vamos -C40 nix32
```
```
3.141590e+00
```

**Comment by TCH68k** [comment]
It works, thank you.
