### ISSUE TITLE
strtoimax is an alias for strtol, but intmax_t is long long (64 bit), not long (32 bit)

### ISSUE THREAD

**Issue by Midar** [bebbo/libnix#35]
$title

I think the proper solution would be to copy strtol.c to strtoll.c, make it use long long and have that alias to strtoimax instead.

Same for strtoull / strtoumax.

**Comment by Midar** [comment]
Seems to work.

Similar to this: strtof is missing

**Comment by bebbo** [comment]
added `strtof` - please test
