### ISSUE TITLE
Printf format string precision problem

### ISSUE THREAD

**Issue by BSzili** [bebbo/libnix#4]
Precision is usually given in a "integer.decimals" format, but it's quite common to omit the first number and just use ".decimals". According to the documentation:
> If the period is specified without an explicit value for precision, 0 is assumed.

This is currently not supported by vfprintf, and it will just print the format string instead. For example:
`printf("Initialized %3.1fM cache\n", (float)(dacachesize/1024.f/1024.f));`
works, but 
`printf("Initialized %.1fM cache\n", (float)(dacachesize/1024.f/1024.f));`
doesn't.

**Comment by bebbo** [comment]
you have to specify `-lm` plus use the fixed Makefile.gcc6^^.

(and the cast to (float) is superfluous, plus it's converted to double...)

**Comment by BSzili** [comment]
I misdiagnosed the problem, because one test case was built before the makefile.gcc6 update. I made sure to update it (make update and then make all in amiga-gcc). It grabbed all the changes and rebuilt the libraries, but now I don't have the float specifiers in either case. I'll try to clone and rebuild libnix from scratch to see if it makes any difference.

**Comment by BSzili** [comment]
This time it definitely rebuilt everything, but the float format strings are still not working for me with this example. I know the float cast is superfluous, but I took this directly from EDuke32, so everything matches up. 
```
#include <stdio.h>
int main(void)
{
	int dacachesize = 21434721;
	printf("Initialized %.1fM cache\n", (float)(dacachesize/1024.f/1024.f));
	printf("Initialized %3.1fM cache\n", (float)(dacachesize/1024.f/1024.f));
	return 0;
}
```

I compiled it like this:
> m68k-amigaos-gcc -noixemul -m68060 -m68881 -o floatprint floatprint.c

**Comment by bebbo** [comment]
> I compiled it like this:
> 
> > m68k-amigaos-gcc -noixemul -m68060 -m68881 -o floatprint floatprint.c

add `-lm`

**Comment by BSzili** [comment]
Oops. I had -lm there (I copied the command wrong), but it wasn't at the end. I re-liked the NBlood executalbe too, and the floating point format strings are fixed now.
