### ISSUE TITLE
locale seems not to work with -noixemul

### ISSUE THREAD

**Issue by githubaf** [bebbo/libnix#41]
Please look at the following test program:

```
/*
 * AF, 21.Jan.2021 HGW
~/opt/m68k-amigaos_10Jan21/bin/m68k-amigaos-gcc -Wall --pedantic -noixemul  point_test.c -o point_test
*/

#include <stdio.h>
#include <locale.h>

int main(void)
{
	printf("Der Dezimalpunkt ist <%s>\n",localeconv()->decimal_point);
	return 0;
}

```
When compiled for linux ist shows the decimal_point as a dot.
When compiled for amiga with -noixemul there is not point.
When I compile without -noixemul the point is there.

I checked with snoopdos and there is no attempt to open the locale.library?

**Comment by bebbo** [comment]
please test

**Comment by githubaf** [comment]
Yes! Now it works. Thank you for fixing it.
