### ISSUE TITLE
%f formatting isn't working

### ISSUE THREAD

**Issue by tehKaiN** [bebbo/libnix#6]
Consider simple test:

``` c
#include <stdio.h>

void main(void) {
	char szFmt[] = "%f";
	
	printf(szFmt, 31415.92f);
}
```

I've stumbled across it during compiling [lhasa](https://github.com/fragglet/lhasa)  which uses %5.1f format for size ratio. `FULL_SPECIFIERS` define seems to toggle `%f` support in libnix, but building does something strange:

```
m68k-amigaos-gcc -I/cygdrive/d/prg/_git/amiga-gcc/projects/libnix/sources/math/../headers -DFULL_SPECIFIERS -Wall -Os -fomit-frame-pointer -fbaserel32 -DSMALL_DATA -m68020 extra/.created stdio/.created stdlib/.created trans/.created ../nix/assert/.created ../nix/stdio/.created /cygdrive/d/prg/_git/amiga-gcc/projects/libnix/sources/math/../nix/stdio/vfprintf.c -c -o stdio/vfprintf.o

// and later

m68k-amigaos-gcc -I/cygdrive/d/prg/_git/amiga-gcc/projects/libnix/sources/nix/../headers -Wall -Os -fomit-frame-pointer -fbaserel32 -DSMALL_DATA -m68020 -m68881 -S /cygdrive/d/prg/_git/amiga-gcc/projects/libnix/sources/nix/stdio/vfprintf.c -o stdio/vfprintf.S 2>&1|tee stdio/vfprintf.err
```

I've changed FULL_SPECIFIERS ifdef to `#if 1` and formatting works, so code is ok - there is some build system fault. I'm not really an automake guy (prefer bare makefiles or CMake) so can't really help, but I guess I've traced it a bit ;)

**Comment by bebbo** [comment]
to support printing of **doubles** you have to link the math lib '-lm'.

It also means you have to provide **double** values not _float_!

**Comment by tehKaiN** [comment]
I'm compiling that example using: `m68k-amigaos-gcc printing.c -o printing -noixemul` and I get `%f` result, same goes if I compile using `m68k-amigaos-gcc printing.c -o printing -noixemul -lm`. Also swapping order of `-lm` and `-noixemul` don't make any change.

Am I doing something horribly wrong?

**Comment by bebbo** [comment]
The math lib's Makefile.in was not adjusted: The new file `__vfprintf_total_size.c` must be added with the appropriate define.

**Comment by tehKaiN** [comment]
So I've did on gcc-amiga toolchain:

```
make update
make clean-libnix
make libnix
```

And then compiled test file. Still outputs "%f" instead of digits. I'm almost certain that I've also tried doing it prior to adding `__vfprintf_total_size.c` and result was the same.

**Comment by bebbo** [comment]
building:
`m68k-amigaos-gcc -noixemul -Os printing.c -o printing -lm`

check:
'm68k-amigaos-objdump -d printing | grep muldf3`

**Comment by tehKaiN** [comment]
Ok, that's only me being a noob. Forgot to specify install prefix during rebuild.

**Comment by bebbo** [comment]
> Ok, that's only me being a noob. Forgot to specify install prefix during rebuild.

I updated amiga-gcc to use global variables. Use
```
export PREFIX=/my/prefix/path
```
in your .bashrc

**Comment by tehKaiN** [comment]
Thanks!
