### ISSUE TITLE
fread in ADoom extremely slow

### ISSUE THREAD

**Issue by mheyer32** [bebbo/libnix#61]
I believe 356b99f9c5a9d463211853e0da56d9b09c681d07 crippled fread's performance by making it read the files byte by byte.

The commit to change __srget to read bytewise doesn't explain why that is the right thing to do, but the function comment

> int __srget(FILE *stream) /* Get next input block */

suggests that the function is supposed to read in blocks, not single bytes.

**Comment by bebbo** [comment]
oh . a side effect^^

`getchar()` tried to read the full buffer, before returning...
... needs a different solution then

**Comment by bebbo** [comment]
should be live in ~1 hour

**Comment by mheyer32** [comment]
Thank you, fread works again :-)
