### ISSUE TITLE
undefined reference to __SaveSP

### ISSUE THREAD

**Issue by BSzili** [bebbo/libnix#63]
__SaveSP seems to be missing from the latest version of the startup code. I think it's this commit that removed it: 3c8823cba914fe0b3004f97772de503470f9b4f1
I was wondering, would it be possible to put it back somewhere? detach.c and swapstack.c uses it, so if they are pulled in I end up with an undefined reference.

**Comment by bebbo** [comment]
aye - forgot the `.globl`- thanks

**Comment by BSzili** [comment]
Thanks that fixed it!
