### ISSUE TITLE
Executable compiled with -mcrt=nix13 crashes on a1000/a500, runs on a500+/a1200

### ISSUE THREAD

**Issue by alexalkis** [bebbo/libnix#7]
[hexdump.zip](https://github.com/bebbo/libnix/files/3061642/hexdump.zip)

Crashes on OS<2.0
I've updated all the toolchain on 9/4/2019 :)

**Comment by bebbo** [comment]
please test

**Comment by alexalkis** [comment]
Yes, fixed.  Thanks!

**Comment by dwhinham** [comment]
If using C99 mode (`-std=c99`) in combination with `-mcrt=nix13` or `-noixemul` then compilation fails with the following error:

```
C:\amiga-gcc>m68k-amigaos-gcc -o hello -std=c99 -mcrt=nix13 hello.c
In file included from hello.c:1:0:
C:/amiga-gcc/m68k-amigaos/libnix/include/stdio.h:234:83: error: unknown type name 'fd_set'
  int __stdargs (*lx_select)(struct _StdFileDes *sfd, int select_cmd, int io_mode, fd_set *, u_long *);
                                                                                   ^~~~~~
C:/amiga-gcc/m68k-amigaos/libnix/include/stdio.h:234:93: error: unknown type name 'u_long'
  int __stdargs (*lx_select)(struct _StdFileDes *sfd, int select_cmd, int io_mode, fd_set *, u_long *);
                                                                                             ^~~~~~
```


Any ideas? 😃

**Comment by alexalkis** [comment]
Reproducible here as well. But maybe you should open a new issue :)

**Comment by dwhinham** [comment]
Thanks - sorry, I thought it was related to this issue. Opening a new one :)

**Comment by alexalkis** [comment]
Well a crash is a bit different that not linking.  Your issue might be more related to this #8 that I just posted.
Looks like that some staff is not pulled in the nix13 libs.

**Comment by alexalkis** [comment]
Hmm, scratch that, your issue is with header files only.
