### ISSUE TITLE
snprintf() broken

### ISSUE THREAD

**Issue by githubaf** [bebbo/libnix#7]
Despite of several improvemts the commit 1c02aa9 form 1.Mar.2018, 19:52 breaks snprintf()

snprinf() now always inserts the ending zero at the maxlen-Position, which is wrong.
Use the following code to verify:

```
/* AF, GWD, 16.Apr2018
m68k-amigaos-gcc af_test.c -noixemul -o af_test_amiga
vamos af_test_amiga
gcc af_test.c -o af_test
./af_test
*/

#include <stdio.h>
#include <string.h>
#include <assert.h>

char Buffer[2000];

int main(void)
{
        int snprinf_retvalue;

        sprintf(Buffer,"Das Pferd frisst keinen Gurkensalat.");
        printf("Buffer = <%s>\n",Buffer);

        snprinf_retvalue=snprintf(Buffer,1024,"%s", "123");

        printf("Buffer = <%s>\n",Buffer);
        printf("snprintf returned %d\n",snprinf_retvalue);

        assert(snprinf_retvalue==3);
        assert(!strcmp(Buffer,"123"));

        return 0;
}
```

I found a module-test for some standard functions here, maybe it' s of interest

http://git.musl-libc.org/cgit/libc-testsuite/tree

**Comment by bebbo** [comment]
Some more tests pass - also your "Pferd" is working now. Please verify.

**Comment by bebbo** [comment]
> I found a module-test for some standard functions here, maybe it' s of interest: http://git.musl-libc.org/cgit/libc-testsuite/tree

Yes, very helpful, thanks

**Comment by githubaf** [comment]
Yes, bug has gone. Great!
