### ISSUE TITLE
Non-fbaserel library builds are dependent on __a4_init

### ISSUE THREAD

**Issue by mheyer32** [bebbo/libnix#73]
https://github.com/bebbo/libnix/blob/00bdd5b16fdfe4b7feb29c774b388477ff715dae/sources/startup/libinit.c#L164

There's code in the library startup to clear out the BSS (which I believe is only there for KS 1.3?). Unfortunately, it references __a4_init even in non-fbaserel builds, which leads to linker errors.

**Comment by bebbo** [comment]
please test
