### ISSUE TITLE
nix13 math linking issues

### ISSUE THREAD

**Issue by alexalkis** [bebbo/libnix#8]
```
#include <stdio.h>
#include <math.h>

int main(int argc, char *argv[])
{
  printf("%f\n", cbrt(9));
  return 0;
}
```
You get linking problems with nix13
```
m68k-amigaos-gcc -o hello -mcrt=nix13 hello.c -lm
/opt/amiga/gcc6/lib/gcc/m68k-amigaos/6.5.0b/../../../../m68k-amigaos/bin/ld: /tmp/ccoSoZST.o:(.text+0x12): undefined reference to `cbrt'
collect2: error: ld returned 1 exit status
```
But if you manually add (a non nix13 lib I assume) it finds the symbol and links (and works)

```
m68k-amigaos-gcc -o hello -mcrt=nix13 hello.c -lm /opt/amiga/gcc6/m68k-amigaos/lib/libm.a
```

**Comment by bebbo** [comment]
I modified the specs to always fallback to the default libm. Since this libm.a has the same name, I added a soft link named lib__m__.a which refers to the default libm.a.

Please test

**Comment by alexalkis** [comment]
Ummm, re-updating the toolchain (to fix my make update-repos mixed up).
The first pull went up back to GB range.  Some --depth went off?
Currently 
[Receiving objects:  23% (491566/2071913), 639.57 MiB | 629.00 KiB/s   ]

23% @ 0.7gb :)
It'll take some time...

**Comment by alexalkis** [comment]
Well, it was taking like a million years. I interrupted and edit makefile to have DEPTH=1 and all was built.

Problem is fixed.  Thanks!
