### ISSUE TITLE
swapstack.o is no longer in libnix*.a

### ISSUE THREAD

**Issue by BSzili** [bebbo/libnix#81]
I tried looking at the recent makefile changes, but I didn't find the cause yet. Could you look into this?

**Comment by BSzili** [comment]
Fixed by ef23522, thank you!

**Comment by BSzili** [comment]
Sorry, I'd like to reopen this as I missed something, and I didn't want to spam new issues. swapstack.o is now in place and __stkinit works as expected, but after the program completes I get a crash at exit. It's possible that I ran into another race condition, or maybe __stkexit is called too early/late? I uploaded a complete test case here: https://bszili.morphos.me/stuff/stacktest2.zip
The source code of the test program separately: https://bszili.morphos.me/stuff/stacktest.c

**Comment by BSzili** [comment]
Thanks for the quick fix! It seems like there is more to this than I initially expected, so the simple test case I made was insufficient. I managed to narrow down the cause to allocating a large variable on the stack and calling exit() instead of returning from the main function. Please have a look at the updated test program:
https://bszili.morphos.me/stuff/stacktest.c
https://bszili.morphos.me/stuff/stacktest

**Comment by bebbo** [comment]
please test

**Comment by BSzili** [comment]
Everything seems to be working now, great work! I'm closing the issue.
