### ISSUE TITLE
Possible memory corruption originating from libnix13

### ISSUE THREAD

**Issue by mankeli** [bebbo/libnix#84]
A mystery blit corrupts chip memory before main() in binary compiled with bebbo-gcc. Investigation by a/b in this [EAB thread](https://eab.abime.net/showthread.php?p=1688241) suggests that there's DOS I/O calls happening when system is disabled.

The code in main() also disables system, but doesn't do any I/O afterwards. I've verified that the chip data is loaded into memory, but then gets stomped by the blit.

CFLAGS for compiling are -mcrt=nix13 -O2 -Wall -mtune=68000. I tried to look for obvious problem in libnix, but could find anything definitive. Stackswap seems to disable system for a short time, and command line parsing uses some Dos calls, and both are added to the libc init list, but not sure why the memory corruption happens.

**Comment by bebbo** [comment]
sorry, that's not enough info to do anything

**Comment by bebbo** [comment]
```
40a10b7c :   007c 4e5d            ORSR.W #$4e5d
40a10b80 :   4e75                 RTS.L
40a10b82 :   303c 0f0f            MOVE.W #$0f0f,d0
40a10b86 :   33c0 00df f180       MOVE.W d0,$00dff180
40a10b8c :   33c0 00df f180       MOVE.W d0,$00dff180
40a10b92 :   60f2                 BT.B #$f2
40a10b94 :   2f0a                 MOVE.L a2,-(a7) [40000014]
40a10b96 :   700a                 MOVE.L #$0a,d0
40a10b98 : * 21c0 0090            MOVE.L d0,$0090.w [00f80c4c]
40a10b9c :   4eb9 40a1 73c8       JSR.L $40a173c8
40a10ba2 :   33fc 7fff 00df f09a  MOVE.W #$7fff,$00dff09a
40a10baa :   33fc 7fff 00df f09c  MOVE.W #$7fff,$00dff09c
40a10bb2 :   33fc 7ff0 00df f096  MOVE.W #$7ff0,$00dff096
40a10bba :   33fc 0000 00df f102  MOVE.W #$0000,$00dff102
40a10bc2 :   3039 00df f004       MOVE.W $00dff004,d0
40a10bc8 :   0800 0000            BTST.L #$0000,d0
40a10bcc :   67f4                 BEQ.B #$f4
```
writing at address 0x00000090 is not part of libnix.

**Comment by bebbo** [comment]
I guess you already disabled `__initlibraries`.

**Comment by bebbo** [comment]
> > I guess you already disabled `__initlibraries`.
> 
> Yeah I tried - it gives "Software error - task held" error from both cli and wb

You should only tinker with internal topics if you are familiar with them and know the consequences.

**__nocommandline** requires a valid **DOSBase** and is called before your __main__ is called. It relies on the fact that **__initlibraries** run before.
And there are more functions which require the **DOSBase** or maybe a different library to be present already.

This isn't a bug in libnix, it's rather a wrong use of libnix.

**Comment by bebbo** [comment]
An out of the box kick13 hello world runs without problems from CLI and Workbench. And it's calling **__initlibraries** plus **__nocommandline**.

Please provide some source with make instructions to prove your claim.

**Comment by bebbo** [comment]
> @bebbo should this ticket be re-opened?

not needed, it's fixed now: The lock is null, which wasn't checked.

**Comment by bebbo** [comment]
> is it fixed in libnix13 too?

yes, you need to run a `make update && make libnix`
