### ISSUE TITLE
Starting from Workbench never reaches main()

### ISSUE THREAD

**Issue by BSzili** [bebbo/libnix#91]
After a recent update I noticed that newly compiled programs don't start from Workbench, I verified this with kprintfs too to make sure it's not an stdio issue. I'm linking to the static version of libnix:
``m68k-amigaos-gcc -noixemul -o main.exe main.c``
This small test program:
```
#include <stdio.h>
int main(int argc, char *argv[])
{
	printf("test\n");
	return 0;
}
```
I uploaded the executable I built in case my setup is broken:
https://bszilli.morphos.me/stuff/main.c
https://bszilli.morphos.me/stuff/main.exe
Did something change regarding the startup code? Thanks for the help in advance!

**Comment by BSzili** [comment]
Oops, i forgot that it needs an icon, please try with this one:
https://bszili.morphos.me/stuff/main.exe.info

**Comment by bebbo** [comment]
ah, yes, libnix.library needed some changes... Thanks for reporting. it's fixed.

**Comment by BSzili** [comment]
That fixed it, thanks!
