### ISSUE TITLE
Auto-open for resources is broken

### ISSUE THREAD

**Issue by mheyer32** [bebbo/libnix#93]
I accidentally triggered auto-open for misc.resource and potgo.resource.
The startup failed with "failed to load misc.resource" and "failed to load potgo.resource", which makes me believe the libnix startup tried to open these as libraries, not resources.

**Comment by bebbo** [comment]
You must utterly detest such things...

**Comment by mheyer32** [comment]
In computer science, there are only two hard problems
1) naming  things
2) cache invalidation
3) off-by-one errors
